/* miniz_export.h - Export macros for miniz
 * This file is typically generated by CMake, but for static linking
 * we just define MINIZ_EXPORT to nothing.
 */
#ifndef MINIZ_EXPORT_H
#define MINIZ_EXPORT_H

#ifndef MINIZ_EXPORT
#define MINIZ_EXPORT
#endif

#endif /* MINIZ_EXPORT_H */
